#kubectl get configmap kube-prometheus-stack-grafana -o yaml

apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    [smtp]
    enabled = true
    host = smtp.gmail.com:587  # SMTP server and port
    user = fusisoft@gmail.com  # Your SMTP username
    password = 'alzy wpgz vess iwwd'  # Your SMTP password
    from_address = fusisoft@gmail.com  # Sender email address
    from_name = Grafana-Alerts
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-10-11T02:56:16Z"
  labels:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.2.1
    helm.sh/chart: grafana-8.5.2
  name: kube-prometheus-stack-grafana
  namespace: default




  k rollout restart deploy kube-prometheus-stack-grafana

